version: "3"

services:
  mavp2p:
    build: mavp2p
    restart: unless-stopped
    network_mode: "host"
    devices:
      - /dev/ttyTHS1:/dev/ttyTHS1

  mqtt:
    build: mqtt
    ports:
      - "18830:18830"
    restart: on-failure

  status:
    build: status
    depends_on:
      - mqtt
    privileged: true
    restart: on-failure

  fcm:
    depends_on:
      - mqtt
      - mavp2p
    build: fcm
    network_mode: "host"
    restart: on-failure

  pcm:
    depends_on:
      - mqtt
    build: pcm
    restart: on-failure
    devices:
      - /dev/ttyACM0:/dev/ttyACM0

  vio:
    depends_on:
      - mqtt
    build: vio
    privileged: true
    restart: on-failure

  apriltag:
    depends_on:
      - mqtt
    build: apriltag
    restart: on-failure
    volumes:
      - /tmp/argus_socket:/tmp/argus_socket

  fusion:
    depends_on:
      - mqtt
      - vio
      - apriltag
    build: fusion
    restart: on-failure

  thermal:
    build: thermal
    depends_on:
      - mqtt
    privileged: true
    restart: on-failure

  # sandbox:
  #   depends_on:
  #     - mqtt
  #   build: sandbox
  #   restart: on-failure
