name: Build Container Thermal

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "VMC/thermal/**"
      - "Libraries/**"
  push:
    branches:
      - main
    paths:
      - "VMC/thermal/**"
      - "Libraries/**"

jobs:
  check:
    uses: ./.github/workflows/container.yml
    with:
      image: "thermal"