name: Build Container PX4

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "PX4/**"
  push:
    branches:
      - main
    paths:
      - "PX4/**"

jobs:
  px4_x86:
    uses: ./.github/workflows/container_x86_64.yml
    with:
      image: "px4"
      context_path: "PX4/docker"
