name: Build Container Fusion

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "VMC/fusion/**"
      - "Libraries/**"
  push:
    branches:
      - main
      - develop
    paths:
      - "VMC/fusion/**"
      - "Libraries/**"

jobs:
  fusion:
    uses: ./.github/workflows/container.yml
    with:
      image: "fusion"