name: Build Container

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

env:
  CONTAINER_PREFIX: "vrc/2022/"

jobs:
  container-build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Copy Libraries
        run: python scripts/copy_libraries.py

      - name: Cache PX4
        if: inputs.image == 'fcm'
        uses: actions/cache@v3
        with:
          path: PX4/build
          key: px4-package-${{ hashFiles('PX4/patches/**') }}-${{ hashFiles('PX4/bell.xml') }}
          restore-keys: |
            px4-package-${{ hashFiles('PX4/patches/**') }}
            px4-package
            px4-firmware-${{ hashFiles('PX4/patches/**') }}
            px4-firmware

      - name: Generate Custom Pymavlink Package
        if: inputs.image == 'fcm'
        run: python3 PX4/generate.py --pymavlink

      - name: Github CR Login
        if: github.event_name != 'pull_request' && inputs.image != 'sandbox'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Container
        uses: docker/build-push-action@v2
        with:
          context: VMC/${{ inputs.image }}
          push: ${{ github.event_name != 'pull_request' && inputs.image != 'sandbox' }}
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.CONTAINER_PREFIX }}${{ inputs.image }}:latest
          platforms: linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Delete Untagged Images
        if: github.event_name != 'pull_request' && inputs.image != 'sandbox'
        uses: vlaurin/action-ghcr-prune@v0.4.0
        with:
          organization: ${{ github.repository_owner }}
          container: ${{ env.CONTAINER_PREFIX }}${{ inputs.image }}
          token: ${{ secrets.GITHUB_TOKEN }}
          untagged-keep-latest: 1
          dry-run: true
          untagged: true
