name: Build Container Status

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "VMC/status/**"
      - "Libraries/**"
  push:
    branches:
      - main
    paths:
      - "VMC/status/**"
      - "Libraries/**"

jobs:
  status:
    uses: ./.github/workflows/container.yml
    with:
      image: "status"