name: Develop Release

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # will manually need to create a release the first time this
      # ever runs.
      - name: Retag Latest
        uses: EndBug/latest-tag@latest
        with:
          tag-name: develop