name: Python Checks VMC VIO

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "VMC/vio/**"
      - "Libraries/**"
      - "requirements.txt"
      - "package-lock.json"

jobs:
  vmc-vio:
    uses: ./.github/workflows/python_checks.yml
    with:
      project: "VMC/vio"