name: Python Checks VMC Fusion

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "VMC/fusion/**"
      - "Libraries/**"
      - "requirements.txt"
      - "package-lock.json"

jobs:
  check:
    uses: ./.github/workflows/python_checks.yml
    with:
      project: "VMC/fusion"