name: Python Checks scripts

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "scripts/**"
      - "requirements.txt"
      - "package-lock.json"

jobs:
  check:
    uses: ./.github/workflows/python_checks.yml
    with:
      project: "scripts"
      cache: false