name: Python Checks PX4

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "PX4/**.py"
      - "requirements.txt"
      - "package-lock.json"

jobs:
  px4:
    uses: ./.github/workflows/python_checks.yml
    with:
      project: "PX4"
      cache: false