name: Python Checks VMC Status

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "VMC/status/**"
      - "Libraries/**"
      - "requirements.txt"
      - "package-lock.json"

jobs:
  vmc-status:
    uses: ./.github/workflows/python_checks.yml
    with:
      project: "VMC/status"