name: Python Checks VMC Apriltag

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "VMC/apriltag/python/**"
      - "requirements.txt"
      - "package-lock.json"

jobs:
  vmc-apriltag:
    uses: ./.github/workflows/python_checks.yml
    with:
      project: "VMC/apriltag/python"