name: Check for Trailing Whitespace

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop

jobs:
  whitespace-check:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Check for Trailing Whitespace
        run: python scripts/check_whitespace.py
